### ISSUE TITLE
Integrate TravisCI into workflow

### ISSUE THREAD

**Issue by user2745** [IoTresor/geo-api#15]
Add TravisCI to the existing workflow
Be able to push + test + deploy EXISTING code

**Comment by dgatto** [comment]
Here's what I found on Operating System differences in Travis.
Seems like we just need to figure out our use case and if just testing for linux is okay.

https://docs.travis-ci.com/user/multi-os/

Also, made some tweaks, Travis builds are passing now. No tests are written against it, but we'll save that for a different Issue. 

https://travis-ci.com/github/IoTresor/geo-api/builds/165362443

**Comment by dgatto** [comment]
So, the builds are working. My next question is more the continuous code integration part of it. Like, dev passes, great, now do we have to manually put a PR in from dev -> qa and from qa -> master every time?

**Comment by dgatto** [comment]
To answer my own question, I think it's a yes.

**Comment by user2745** [comment]
I see where this is headed 
what if there was a way to automate from dev -> qa -> master?
