### ISSUE TITLE
Branch Naming Conventions

### ISSUE THREAD

**Issue by user2745** [IoTresor/geo-api#7]
@dgatto  Rename LIVE to MASTER
and setup DEV & QA branches

We're aiming to set up continuous integration practices

**Comment by user2745** [comment]
Hey How can I help with this ?

**Comment by dgatto** [comment]
It’s a pretty easy process I just hadn’t started on it yet. Was doing the typescript stuff first.

You’re welcome to do it, though.

We pretty much just need 3 main branches.
- master (which is your current **live**)
- qa (this one isn’t as necessary in such a small project so honestly it’s up for debate if we even need it)
- dev

If you can just reorganize our current branch structure to have those 3, that’s pretty much it.

**Comment by dgatto** [comment]
@user2745  So you actually have to go to your Settings tab and change the default branch to the master one that I just pushed.

<img width="716" alt="Screen Shot 2020-05-10 at 1 37 02 AM" src="https://user-images.githubusercontent.com/11690479/81491657-c94bf180-925e-11ea-9360-37ac76fcb196.png">

**Comment by user2745** [comment]
All Done so  far --
I am going to create a QA branch because this project will definitely grow in the future
I am going to merge all the different branches we have now, into dev

**Comment by dgatto** [comment]
Sounds good, if the branch has already been merged on a PR then just delete it.
